//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public Siniflar()
        {
            this.Ogrenciler = new HashSet<Ogrenciler>();
            this.Yoklama = new HashSet<Yoklama>();
        }
    
        public int sinifId { get; set; }
        public string sinifAdi { get; set; }
        public int sinifkapasite { get; set; }
        public int ögretmenId { get; set; }
    
        public virtual DersTablo DersTablo { get; set; }
        public virtual ICollection<Ogrenciler> Ogrenciler { get; set; }
        public virtual ICollection<Yoklama> Yoklama { get; set; }
    }
}
