//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluBilisim.AnaOkuluService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yemekler", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Yemekler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnaYemekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorbaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TatliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YemekIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnaYemek {
            get {
                return this.AnaYemekField;
            }
            set {
                if ((object.ReferenceEquals(this.AnaYemekField, value) != true)) {
                    this.AnaYemekField = value;
                    this.RaisePropertyChanged("AnaYemek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Corba {
            get {
                return this.CorbaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorbaField, value) != true)) {
                    this.CorbaField = value;
                    this.RaisePropertyChanged("Corba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tatli {
            get {
                return this.TatliField;
            }
            set {
                if ((object.ReferenceEquals(this.TatliField, value) != true)) {
                    this.TatliField = value;
                    this.RaisePropertyChanged("Tatli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YemekId {
            get {
                return this.YemekIdField;
            }
            set {
                if ((this.YemekIdField.Equals(value) != true)) {
                    this.YemekIdField = value;
                    this.RaisePropertyChanged("YemekId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Siniflar", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Siniflar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Ogrenciler[] OgrencilersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Personeller PersonellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Yoklama[] YoklamasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sinifAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sinifIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> sinifkapasiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ögretmenIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Ogrenciler[] Ogrencilers {
            get {
                return this.OgrencilersField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrencilersField, value) != true)) {
                    this.OgrencilersField = value;
                    this.RaisePropertyChanged("Ogrencilers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Personeller Personeller {
            get {
                return this.PersonellerField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonellerField, value) != true)) {
                    this.PersonellerField = value;
                    this.RaisePropertyChanged("Personeller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Yoklama[] Yoklamas {
            get {
                return this.YoklamasField;
            }
            set {
                if ((object.ReferenceEquals(this.YoklamasField, value) != true)) {
                    this.YoklamasField = value;
                    this.RaisePropertyChanged("Yoklamas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sinifAdi {
            get {
                return this.sinifAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.sinifAdiField, value) != true)) {
                    this.sinifAdiField = value;
                    this.RaisePropertyChanged("sinifAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sinifId {
            get {
                return this.sinifIdField;
            }
            set {
                if ((this.sinifIdField.Equals(value) != true)) {
                    this.sinifIdField = value;
                    this.RaisePropertyChanged("sinifId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> sinifkapasite {
            get {
                return this.sinifkapasiteField;
            }
            set {
                if ((this.sinifkapasiteField.Equals(value) != true)) {
                    this.sinifkapasiteField = value;
                    this.RaisePropertyChanged("sinifkapasite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ögretmenId {
            get {
                return this.ögretmenIdField;
            }
            set {
                if ((this.ögretmenIdField.Equals(value) != true)) {
                    this.ögretmenIdField = value;
                    this.RaisePropertyChanged("ögretmenId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personeller", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Personeller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AskerlikDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AyrilisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BaslamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BasvuruTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EgitimDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KSiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KVerilisYeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KaileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KanGrubuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KciltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KcinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> KdogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdogumYeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdogumilceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdogumiliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KkimlikSeriNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KkoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KmahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KtcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KuyrukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SicilNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Siniflar[] SiniflarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TecilBitisYiliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AskerlikDurumu {
            get {
                return this.AskerlikDurumuField;
            }
            set {
                if ((object.ReferenceEquals(this.AskerlikDurumuField, value) != true)) {
                    this.AskerlikDurumuField = value;
                    this.RaisePropertyChanged("AskerlikDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AyrilisTarihi {
            get {
                return this.AyrilisTarihiField;
            }
            set {
                if ((this.AyrilisTarihiField.Equals(value) != true)) {
                    this.AyrilisTarihiField = value;
                    this.RaisePropertyChanged("AyrilisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BaslamaTarihi {
            get {
                return this.BaslamaTarihiField;
            }
            set {
                if ((this.BaslamaTarihiField.Equals(value) != true)) {
                    this.BaslamaTarihiField = value;
                    this.RaisePropertyChanged("BaslamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BasvuruTarihi {
            get {
                return this.BasvuruTarihiField;
            }
            set {
                if ((this.BasvuruTarihiField.Equals(value) != true)) {
                    this.BasvuruTarihiField = value;
                    this.RaisePropertyChanged("BasvuruTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CepTel {
            get {
                return this.CepTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CepTelField, value) != true)) {
                    this.CepTelField = value;
                    this.RaisePropertyChanged("CepTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departman {
            get {
                return this.DepartmanField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmanField, value) != true)) {
                    this.DepartmanField = value;
                    this.RaisePropertyChanged("Departman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EgitimDurumu {
            get {
                return this.EgitimDurumuField;
            }
            set {
                if ((object.ReferenceEquals(this.EgitimDurumuField, value) != true)) {
                    this.EgitimDurumuField = value;
                    this.RaisePropertyChanged("EgitimDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvTel {
            get {
                return this.EvTelField;
            }
            set {
                if ((object.ReferenceEquals(this.EvTelField, value) != true)) {
                    this.EvTelField = value;
                    this.RaisePropertyChanged("EvTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KKayitNo {
            get {
                return this.KKayitNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KKayitNoField, value) != true)) {
                    this.KKayitNoField = value;
                    this.RaisePropertyChanged("KKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSiraNo {
            get {
                return this.KSiraNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KSiraNoField, value) != true)) {
                    this.KSiraNoField = value;
                    this.RaisePropertyChanged("KSiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KVerilisYeri {
            get {
                return this.KVerilisYeriField;
            }
            set {
                if ((object.ReferenceEquals(this.KVerilisYeriField, value) != true)) {
                    this.KVerilisYeriField = value;
                    this.RaisePropertyChanged("KVerilisYeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kaile {
            get {
                return this.KaileField;
            }
            set {
                if ((object.ReferenceEquals(this.KaileField, value) != true)) {
                    this.KaileField = value;
                    this.RaisePropertyChanged("Kaile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KanGrubu {
            get {
                return this.KanGrubuField;
            }
            set {
                if ((object.ReferenceEquals(this.KanGrubuField, value) != true)) {
                    this.KanGrubuField = value;
                    this.RaisePropertyChanged("KanGrubu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kcilt {
            get {
                return this.KciltField;
            }
            set {
                if ((object.ReferenceEquals(this.KciltField, value) != true)) {
                    this.KciltField = value;
                    this.RaisePropertyChanged("Kcilt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kcinsiyet {
            get {
                return this.KcinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.KcinsiyetField, value) != true)) {
                    this.KcinsiyetField = value;
                    this.RaisePropertyChanged("Kcinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> KdogumTarihi {
            get {
                return this.KdogumTarihiField;
            }
            set {
                if ((this.KdogumTarihiField.Equals(value) != true)) {
                    this.KdogumTarihiField = value;
                    this.RaisePropertyChanged("KdogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KdogumYeri {
            get {
                return this.KdogumYeriField;
            }
            set {
                if ((object.ReferenceEquals(this.KdogumYeriField, value) != true)) {
                    this.KdogumYeriField = value;
                    this.RaisePropertyChanged("KdogumYeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kdogumilce {
            get {
                return this.KdogumilceField;
            }
            set {
                if ((object.ReferenceEquals(this.KdogumilceField, value) != true)) {
                    this.KdogumilceField = value;
                    this.RaisePropertyChanged("Kdogumilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kdogumili {
            get {
                return this.KdogumiliField;
            }
            set {
                if ((object.ReferenceEquals(this.KdogumiliField, value) != true)) {
                    this.KdogumiliField = value;
                    this.RaisePropertyChanged("Kdogumili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KkimlikSeriNo {
            get {
                return this.KkimlikSeriNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KkimlikSeriNoField, value) != true)) {
                    this.KkimlikSeriNoField = value;
                    this.RaisePropertyChanged("KkimlikSeriNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kkoy {
            get {
                return this.KkoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KkoyField, value) != true)) {
                    this.KkoyField = value;
                    this.RaisePropertyChanged("Kkoy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kmahalle {
            get {
                return this.KmahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.KmahalleField, value) != true)) {
                    this.KmahalleField = value;
                    this.RaisePropertyChanged("Kmahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KtcNo {
            get {
                return this.KtcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KtcNoField, value) != true)) {
                    this.KtcNoField = value;
                    this.RaisePropertyChanged("KtcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kuyruk {
            get {
                return this.KuyrukField;
            }
            set {
                if ((object.ReferenceEquals(this.KuyrukField, value) != true)) {
                    this.KuyrukField = value;
                    this.RaisePropertyChanged("Kuyruk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonelId {
            get {
                return this.PersonelIdField;
            }
            set {
                if ((this.PersonelIdField.Equals(value) != true)) {
                    this.PersonelIdField = value;
                    this.RaisePropertyChanged("PersonelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semt {
            get {
                return this.SemtField;
            }
            set {
                if ((object.ReferenceEquals(this.SemtField, value) != true)) {
                    this.SemtField = value;
                    this.RaisePropertyChanged("Semt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SicilNo {
            get {
                return this.SicilNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SicilNoField, value) != true)) {
                    this.SicilNoField = value;
                    this.RaisePropertyChanged("SicilNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Siniflar[] Siniflars {
            get {
                return this.SiniflarsField;
            }
            set {
                if ((object.ReferenceEquals(this.SiniflarsField, value) != true)) {
                    this.SiniflarsField = value;
                    this.RaisePropertyChanged("Siniflars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TecilBitisYili {
            get {
                return this.TecilBitisYiliField;
            }
            set {
                if ((object.ReferenceEquals(this.TecilBitisYiliField, value) != true)) {
                    this.TecilBitisYiliField = value;
                    this.RaisePropertyChanged("TecilBitisYili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string il {
            get {
                return this.ilField;
            }
            set {
                if ((object.ReferenceEquals(this.ilField, value) != true)) {
                    this.ilField = value;
                    this.RaisePropertyChanged("il");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogrenciler", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Ogrenciler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlerjilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmeliyatlarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CikisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DavranisSorunuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumYeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumilceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumiliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FobileriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GecirdigiHastaliklarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KanGrubuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> KayitTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KimlikSeriNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtezField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ResimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuhsalDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaglikSorunlariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServisIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Servisler ServislerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevdigiYiyeceklerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SinifIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Siniflar SiniflarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.UcuncuSahislar[] UcuncuSahislarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UyrukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Veliler[] VelilersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerilisYeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YapilanlarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YasitlariylaIliskisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ilacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ilceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aile {
            get {
                return this.AileField;
            }
            set {
                if ((object.ReferenceEquals(this.AileField, value) != true)) {
                    this.AileField = value;
                    this.RaisePropertyChanged("Aile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alerjiler {
            get {
                return this.AlerjilerField;
            }
            set {
                if ((object.ReferenceEquals(this.AlerjilerField, value) != true)) {
                    this.AlerjilerField = value;
                    this.RaisePropertyChanged("Alerjiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ameliyatlar {
            get {
                return this.AmeliyatlarField;
            }
            set {
                if ((object.ReferenceEquals(this.AmeliyatlarField, value) != true)) {
                    this.AmeliyatlarField = value;
                    this.RaisePropertyChanged("Ameliyatlar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asilar {
            get {
                return this.AsilarField;
            }
            set {
                if ((object.ReferenceEquals(this.AsilarField, value) != true)) {
                    this.AsilarField = value;
                    this.RaisePropertyChanged("Asilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CikisTarihi {
            get {
                return this.CikisTarihiField;
            }
            set {
                if ((this.CikisTarihiField.Equals(value) != true)) {
                    this.CikisTarihiField = value;
                    this.RaisePropertyChanged("CikisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cilt {
            get {
                return this.CiltField;
            }
            set {
                if ((object.ReferenceEquals(this.CiltField, value) != true)) {
                    this.CiltField = value;
                    this.RaisePropertyChanged("Cilt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DavranisSorunu {
            get {
                return this.DavranisSorunuField;
            }
            set {
                if ((object.ReferenceEquals(this.DavranisSorunuField, value) != true)) {
                    this.DavranisSorunuField = value;
                    this.RaisePropertyChanged("DavranisSorunu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diyet {
            get {
                return this.DiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.DiyetField, value) != true)) {
                    this.DiyetField = value;
                    this.RaisePropertyChanged("Diyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYeri {
            get {
                return this.DogumYeriField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumYeriField, value) != true)) {
                    this.DogumYeriField = value;
                    this.RaisePropertyChanged("DogumYeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dogumilce {
            get {
                return this.DogumilceField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumilceField, value) != true)) {
                    this.DogumilceField = value;
                    this.RaisePropertyChanged("Dogumilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dogumili {
            get {
                return this.DogumiliField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumiliField, value) != true)) {
                    this.DogumiliField = value;
                    this.RaisePropertyChanged("Dogumili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvTel {
            get {
                return this.EvTelField;
            }
            set {
                if ((object.ReferenceEquals(this.EvTelField, value) != true)) {
                    this.EvTelField = value;
                    this.RaisePropertyChanged("EvTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fobileri {
            get {
                return this.FobileriField;
            }
            set {
                if ((object.ReferenceEquals(this.FobileriField, value) != true)) {
                    this.FobileriField = value;
                    this.RaisePropertyChanged("Fobileri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GecirdigiHastaliklar {
            get {
                return this.GecirdigiHastaliklarField;
            }
            set {
                if ((object.ReferenceEquals(this.GecirdigiHastaliklarField, value) != true)) {
                    this.GecirdigiHastaliklarField = value;
                    this.RaisePropertyChanged("GecirdigiHastaliklar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KanGrubu {
            get {
                return this.KanGrubuField;
            }
            set {
                if ((object.ReferenceEquals(this.KanGrubuField, value) != true)) {
                    this.KanGrubuField = value;
                    this.RaisePropertyChanged("KanGrubu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KayitNo {
            get {
                return this.KayitNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitNoField, value) != true)) {
                    this.KayitNoField = value;
                    this.RaisePropertyChanged("KayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> KayitTarihi {
            get {
                return this.KayitTarihiField;
            }
            set {
                if ((this.KayitTarihiField.Equals(value) != true)) {
                    this.KayitTarihiField = value;
                    this.RaisePropertyChanged("KayitTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KimlikSeriNo {
            get {
                return this.KimlikSeriNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KimlikSeriNoField, value) != true)) {
                    this.KimlikSeriNoField = value;
                    this.RaisePropertyChanged("KimlikSeriNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy {
            get {
                return this.KoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyField, value) != true)) {
                    this.KoyField = value;
                    this.RaisePropertyChanged("Koy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostaKodu {
            get {
                return this.PostaKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.PostaKoduField, value) != true)) {
                    this.PostaKoduField = value;
                    this.RaisePropertyChanged("PostaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Protez {
            get {
                return this.ProtezField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtezField, value) != true)) {
                    this.ProtezField = value;
                    this.RaisePropertyChanged("Protez");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Resim {
            get {
                return this.ResimField;
            }
            set {
                if ((object.ReferenceEquals(this.ResimField, value) != true)) {
                    this.ResimField = value;
                    this.RaisePropertyChanged("Resim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuhsalDurum {
            get {
                return this.RuhsalDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.RuhsalDurumField, value) != true)) {
                    this.RuhsalDurumField = value;
                    this.RaisePropertyChanged("RuhsalDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaglikSorunlari {
            get {
                return this.SaglikSorunlariField;
            }
            set {
                if ((object.ReferenceEquals(this.SaglikSorunlariField, value) != true)) {
                    this.SaglikSorunlariField = value;
                    this.RaisePropertyChanged("SaglikSorunlari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semt {
            get {
                return this.SemtField;
            }
            set {
                if ((object.ReferenceEquals(this.SemtField, value) != true)) {
                    this.SemtField = value;
                    this.RaisePropertyChanged("Semt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServisId {
            get {
                return this.ServisIdField;
            }
            set {
                if ((this.ServisIdField.Equals(value) != true)) {
                    this.ServisIdField = value;
                    this.RaisePropertyChanged("ServisId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Servisler Servisler {
            get {
                return this.ServislerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServislerField, value) != true)) {
                    this.ServislerField = value;
                    this.RaisePropertyChanged("Servisler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SevdigiYiyecekler {
            get {
                return this.SevdigiYiyeceklerField;
            }
            set {
                if ((object.ReferenceEquals(this.SevdigiYiyeceklerField, value) != true)) {
                    this.SevdigiYiyeceklerField = value;
                    this.RaisePropertyChanged("SevdigiYiyecekler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SinifId {
            get {
                return this.SinifIdField;
            }
            set {
                if ((this.SinifIdField.Equals(value) != true)) {
                    this.SinifIdField = value;
                    this.RaisePropertyChanged("SinifId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Siniflar Siniflar {
            get {
                return this.SiniflarField;
            }
            set {
                if ((object.ReferenceEquals(this.SiniflarField, value) != true)) {
                    this.SiniflarField = value;
                    this.RaisePropertyChanged("Siniflar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiraNo {
            get {
                return this.SiraNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SiraNoField, value) != true)) {
                    this.SiraNoField = value;
                    this.RaisePropertyChanged("SiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.UcuncuSahislar[] UcuncuSahislar {
            get {
                return this.UcuncuSahislarField;
            }
            set {
                if ((object.ReferenceEquals(this.UcuncuSahislarField, value) != true)) {
                    this.UcuncuSahislarField = value;
                    this.RaisePropertyChanged("UcuncuSahislar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uyruk {
            get {
                return this.UyrukField;
            }
            set {
                if ((object.ReferenceEquals(this.UyrukField, value) != true)) {
                    this.UyrukField = value;
                    this.RaisePropertyChanged("Uyruk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Veliler[] Velilers {
            get {
                return this.VelilersField;
            }
            set {
                if ((object.ReferenceEquals(this.VelilersField, value) != true)) {
                    this.VelilersField = value;
                    this.RaisePropertyChanged("Velilers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerilisYeri {
            get {
                return this.VerilisYeriField;
            }
            set {
                if ((object.ReferenceEquals(this.VerilisYeriField, value) != true)) {
                    this.VerilisYeriField = value;
                    this.RaisePropertyChanged("VerilisYeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yapilanlar {
            get {
                return this.YapilanlarField;
            }
            set {
                if ((object.ReferenceEquals(this.YapilanlarField, value) != true)) {
                    this.YapilanlarField = value;
                    this.RaisePropertyChanged("Yapilanlar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YasitlariylaIliskisi {
            get {
                return this.YasitlariylaIliskisiField;
            }
            set {
                if ((object.ReferenceEquals(this.YasitlariylaIliskisiField, value) != true)) {
                    this.YasitlariylaIliskisiField = value;
                    this.RaisePropertyChanged("YasitlariylaIliskisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string il {
            get {
                return this.ilField;
            }
            set {
                if ((object.ReferenceEquals(this.ilField, value) != true)) {
                    this.ilField = value;
                    this.RaisePropertyChanged("il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ilac {
            get {
                return this.ilacField;
            }
            set {
                if ((object.ReferenceEquals(this.ilacField, value) != true)) {
                    this.ilacField = value;
                    this.RaisePropertyChanged("ilac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ilce {
            get {
                return this.ilceField;
            }
            set {
                if ((object.ReferenceEquals(this.ilceField, value) != true)) {
                    this.ilceField = value;
                    this.RaisePropertyChanged("ilce");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yoklama", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Yoklama : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevamsizlikTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SinifIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Siniflar SiniflarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevamsizlikTuru {
            get {
                return this.DevamsizlikTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.DevamsizlikTuruField, value) != true)) {
                    this.DevamsizlikTuruField = value;
                    this.RaisePropertyChanged("DevamsizlikTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SinifID {
            get {
                return this.SinifIDField;
            }
            set {
                if ((this.SinifIDField.Equals(value) != true)) {
                    this.SinifIDField = value;
                    this.RaisePropertyChanged("SinifID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Siniflar Siniflar {
            get {
                return this.SiniflarField;
            }
            set {
                if ((object.ReferenceEquals(this.SiniflarField, value) != true)) {
                    this.SiniflarField = value;
                    this.RaisePropertyChanged("Siniflar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servisler", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Servisler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Ogrenciler[] OgrencilersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServisAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServisIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Ogrenciler[] Ogrencilers {
            get {
                return this.OgrencilersField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrencilersField, value) != true)) {
                    this.OgrencilersField = value;
                    this.RaisePropertyChanged("Ogrencilers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServisAdi {
            get {
                return this.ServisAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.ServisAdiField, value) != true)) {
                    this.ServisAdiField = value;
                    this.RaisePropertyChanged("ServisAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServisID {
            get {
                return this.ServisIDField;
            }
            set {
                if ((this.ServisIDField.Equals(value) != true)) {
                    this.ServisIDField = value;
                    this.RaisePropertyChanged("ServisID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UcuncuSahislar", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class UcuncuSahislar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeptelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeslekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Ogrenciler OgrencilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YakinlikDerecesiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ceptel {
            get {
                return this.CeptelField;
            }
            set {
                if ((object.ReferenceEquals(this.CeptelField, value) != true)) {
                    this.CeptelField = value;
                    this.RaisePropertyChanged("Ceptel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvTel {
            get {
                return this.EvTelField;
            }
            set {
                if ((object.ReferenceEquals(this.EvTelField, value) != true)) {
                    this.EvTelField = value;
                    this.RaisePropertyChanged("EvTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meslek {
            get {
                return this.MeslekField;
            }
            set {
                if ((object.ReferenceEquals(this.MeslekField, value) != true)) {
                    this.MeslekField = value;
                    this.RaisePropertyChanged("Meslek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Ogrenciler Ogrenciler {
            get {
                return this.OgrencilerField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrencilerField, value) != true)) {
                    this.OgrencilerField = value;
                    this.RaisePropertyChanged("Ogrenciler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YakinlikDerecesi {
            get {
                return this.YakinlikDerecesiField;
            }
            set {
                if ((object.ReferenceEquals(this.YakinlikDerecesiField, value) != true)) {
                    this.YakinlikDerecesiField = value;
                    this.RaisePropertyChanged("YakinlikDerecesi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veliler", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class Veliler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeptelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeslekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OgrenciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnaOkuluBilisim.AnaOkuluService.Ogrenciler OgrencilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YakinlikDerecesiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ceptel {
            get {
                return this.CeptelField;
            }
            set {
                if ((object.ReferenceEquals(this.CeptelField, value) != true)) {
                    this.CeptelField = value;
                    this.RaisePropertyChanged("Ceptel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvTel {
            get {
                return this.EvTelField;
            }
            set {
                if ((object.ReferenceEquals(this.EvTelField, value) != true)) {
                    this.EvTelField = value;
                    this.RaisePropertyChanged("EvTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meslek {
            get {
                return this.MeslekField;
            }
            set {
                if ((object.ReferenceEquals(this.MeslekField, value) != true)) {
                    this.MeslekField = value;
                    this.RaisePropertyChanged("Meslek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciId {
            get {
                return this.OgrenciIdField;
            }
            set {
                if ((this.OgrenciIdField.Equals(value) != true)) {
                    this.OgrenciIdField = value;
                    this.RaisePropertyChanged("OgrenciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnaOkuluBilisim.AnaOkuluService.Ogrenciler Ogrenciler {
            get {
                return this.OgrencilerField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrencilerField, value) != true)) {
                    this.OgrencilerField = value;
                    this.RaisePropertyChanged("Ogrenciler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YakinlikDerecesi {
            get {
                return this.YakinlikDerecesiField;
            }
            set {
                if ((object.ReferenceEquals(this.YakinlikDerecesiField, value) != true)) {
                    this.YakinlikDerecesiField = value;
                    this.RaisePropertyChanged("YakinlikDerecesi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgretmelerDB", Namespace="http://schemas.datacontract.org/2004/07/AnaOkuluWebService")]
    [System.SerializableAttribute()]
    public partial class OgretmelerDB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOYADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AD {
            get {
                return this.ADField;
            }
            set {
                if ((object.ReferenceEquals(this.ADField, value) != true)) {
                    this.ADField = value;
                    this.RaisePropertyChanged("AD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOYAD {
            get {
                return this.SOYADField;
            }
            set {
                if ((object.ReferenceEquals(this.SOYADField, value) != true)) {
                    this.SOYADField = value;
                    this.RaisePropertyChanged("SOYAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TC {
            get {
                return this.TCField;
            }
            set {
                if ((object.ReferenceEquals(this.TCField, value) != true)) {
                    this.TCField = value;
                    this.RaisePropertyChanged("TC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnaOkuluService.IAnaOkuluWebService")]
    public interface IAnaOkuluWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/GirisKontrol", ReplyAction="http://tempuri.org/IAnaOkuluWebService/GirisKontrolResponse")]
        bool GirisKontrol(string userid, string userpass, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/ParolaDegistir", ReplyAction="http://tempuri.org/IAnaOkuluWebService/ParolaDegistirResponse")]
        bool ParolaDegistir(string oldpassword, string createpassword, string userid, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/TumYemekler", ReplyAction="http://tempuri.org/IAnaOkuluWebService/TumYemeklerResponse")]
        AnaOkuluBilisim.AnaOkuluService.Yemekler[] TumYemekler(string userid, string userpass, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/VeliEmailler", ReplyAction="http://tempuri.org/IAnaOkuluWebService/VeliEmaillerResponse")]
        string[] VeliEmailler(string userid, string userpass, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/YemekEkle", ReplyAction="http://tempuri.org/IAnaOkuluWebService/YemekEkleResponse")]
        bool YemekEkle(string userid, string userpass, string departman, string corba, string anayemek, string tatli, string tarih);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/YemekSil", ReplyAction="http://tempuri.org/IAnaOkuluWebService/YemekSilResponse")]
        bool YemekSil(string userid, string userpass, string departman, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/TumSiniflar", ReplyAction="http://tempuri.org/IAnaOkuluWebService/TumSiniflarResponse")]
        AnaOkuluBilisim.AnaOkuluService.Siniflar[] TumSiniflar(string userid, string userpass, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/TumOgretmenler", ReplyAction="http://tempuri.org/IAnaOkuluWebService/TumOgretmenlerResponse")]
        AnaOkuluBilisim.AnaOkuluService.OgretmelerDB[] TumOgretmenler(string userid, string userpass, string departman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/SinifSil", ReplyAction="http://tempuri.org/IAnaOkuluWebService/SinifSilResponse")]
        bool SinifSil(string userid, string userpass, string departman, int sinifid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/SinifEkle", ReplyAction="http://tempuri.org/IAnaOkuluWebService/SinifEkleResponse")]
        bool SinifEkle(string userid, string userpass, string departman, string sinifadi, int sinifkapasitesi, int ogretmenid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaOkuluWebService/DemirbasGunceller", ReplyAction="http://tempuri.org/IAnaOkuluWebService/DemirbasGuncellerResponse")]
        bool DemirbasGunceller(
                    string userid, 
                    string userpass, 
                    string departman, 
                    int demirbasid, 
                    string DemirbasAdi, 
                    string DemirbasTuru, 
                    string DemirbasCinsi, 
                    string DemirbasAdeti, 
                    string DemirbasBirimi, 
                    string AlindigiYer, 
                    string AlisTarihi, 
                    string GirisTutari, 
                    string AlisFaturaNo, 
                    string KdvOrani, 
                    string KdvTutari, 
                    string SatisYeri, 
                    string SatisTarihi, 
                    string SatisTutari, 
                    string SatisFaturaNo, 
                    string SatisKdvTutari, 
                    string SatisNedeni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnaOkuluWebServiceChannel : AnaOkuluBilisim.AnaOkuluService.IAnaOkuluWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnaOkuluWebServiceClient : System.ServiceModel.ClientBase<AnaOkuluBilisim.AnaOkuluService.IAnaOkuluWebService>, AnaOkuluBilisim.AnaOkuluService.IAnaOkuluWebService {
        
        public AnaOkuluWebServiceClient() {
        }
        
        public AnaOkuluWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnaOkuluWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnaOkuluWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnaOkuluWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GirisKontrol(string userid, string userpass, string departman) {
            return base.Channel.GirisKontrol(userid, userpass, departman);
        }
        
        public bool ParolaDegistir(string oldpassword, string createpassword, string userid, string departman) {
            return base.Channel.ParolaDegistir(oldpassword, createpassword, userid, departman);
        }
        
        public AnaOkuluBilisim.AnaOkuluService.Yemekler[] TumYemekler(string userid, string userpass, string departman) {
            return base.Channel.TumYemekler(userid, userpass, departman);
        }
        
        public string[] VeliEmailler(string userid, string userpass, string departman) {
            return base.Channel.VeliEmailler(userid, userpass, departman);
        }
        
        public bool YemekEkle(string userid, string userpass, string departman, string corba, string anayemek, string tatli, string tarih) {
            return base.Channel.YemekEkle(userid, userpass, departman, corba, anayemek, tatli, tarih);
        }
        
        public bool YemekSil(string userid, string userpass, string departman, int id) {
            return base.Channel.YemekSil(userid, userpass, departman, id);
        }
        
        public AnaOkuluBilisim.AnaOkuluService.Siniflar[] TumSiniflar(string userid, string userpass, string departman) {
            return base.Channel.TumSiniflar(userid, userpass, departman);
        }
        
        public AnaOkuluBilisim.AnaOkuluService.OgretmelerDB[] TumOgretmenler(string userid, string userpass, string departman) {
            return base.Channel.TumOgretmenler(userid, userpass, departman);
        }
        
        public bool SinifSil(string userid, string userpass, string departman, int sinifid) {
            return base.Channel.SinifSil(userid, userpass, departman, sinifid);
        }
        
        public bool SinifEkle(string userid, string userpass, string departman, string sinifadi, int sinifkapasitesi, int ogretmenid) {
            return base.Channel.SinifEkle(userid, userpass, departman, sinifadi, sinifkapasitesi, ogretmenid);
        }
        
        public bool DemirbasGunceller(
                    string userid, 
                    string userpass, 
                    string departman, 
                    int demirbasid, 
                    string DemirbasAdi, 
                    string DemirbasTuru, 
                    string DemirbasCinsi, 
                    string DemirbasAdeti, 
                    string DemirbasBirimi, 
                    string AlindigiYer, 
                    string AlisTarihi, 
                    string GirisTutari, 
                    string AlisFaturaNo, 
                    string KdvOrani, 
                    string KdvTutari, 
                    string SatisYeri, 
                    string SatisTarihi, 
                    string SatisTutari, 
                    string SatisFaturaNo, 
                    string SatisKdvTutari, 
                    string SatisNedeni) {
            return base.Channel.DemirbasGunceller(userid, userpass, departman, demirbasid, DemirbasAdi, DemirbasTuru, DemirbasCinsi, DemirbasAdeti, DemirbasBirimi, AlindigiYer, AlisTarihi, GirisTutari, AlisFaturaNo, KdvOrani, KdvTutari, SatisYeri, SatisTarihi, SatisTutari, SatisFaturaNo, SatisKdvTutari, SatisNedeni);
        }
    }
}
