//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int OgrenciId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Adres { get; set; }
        public string Semt { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
        public string PostaKodu { get; set; }
        public string EvTel { get; set; }
        public string KanGrubu { get; set; }
        public string TcNo { get; set; }
        public string Uyruk { get; set; }
        public string Cinsiyet { get; set; }
        public string KimlikSeriNo { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Dogumili { get; set; }
        public string Dogumilce { get; set; }
        public string Mahalle { get; set; }
        public string Koy { get; set; }
        public string Cilt { get; set; }
        public string Aile { get; set; }
        public string SiraNo { get; set; }
        public string VerilisYeri { get; set; }
        public string KayitNo { get; set; }
        public byte[] Resim { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public int SinifId { get; set; }
        public int ServisId { get; set; }
        public string DavranisSorunu { get; set; }
        public string Yapilanlar { get; set; }
        public string YasitlariylaIliskisi { get; set; }
        public string Fobileri { get; set; }
        public string SevdigiYiyecekler { get; set; }
        public string Asilar { get; set; }
        public string GecirdigiHastaliklar { get; set; }
        public string Alerjiler { get; set; }
        public string Ameliyatlar { get; set; }
        public string SaglikSorunlari { get; set; }
        public string ilac { get; set; }
        public string Protez { get; set; }
        public string Diyet { get; set; }
        public string RuhsalDurum { get; set; }
    
        public virtual Servisler Servisler { get; set; }
        public virtual Siniflar Siniflar { get; set; }
    }
}
