//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public Personeller()
        {
            this.Siniflars = new HashSet<Siniflar>();
        }
    
        public int PersonelId { get; set; }
        public string TcNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string SicilNo { get; set; }
        public Nullable<System.DateTime> BasvuruTarihi { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public string AskerlikDurumu { get; set; }
        public string TecilBitisYili { get; set; }
        public string KanGrubu { get; set; }
        public string Cinsiyet { get; set; }
        public string Adres { get; set; }
        public string Semt { get; set; }
        public string Ilce { get; set; }
        public string il { get; set; }
        public string Mail { get; set; }
        public string EvTel { get; set; }
        public string CepTel { get; set; }
        public string EgitimDurumu { get; set; }
        public Nullable<System.DateTime> AyrilisTarihi { get; set; }
        public string Departman { get; set; }
        public string KtcNo { get; set; }
        public string Kuyruk { get; set; }
        public string Kcinsiyet { get; set; }
        public string KkimlikSeriNo { get; set; }
        public string KdogumYeri { get; set; }
        public Nullable<System.DateTime> KdogumTarihi { get; set; }
        public string Kdogumili { get; set; }
        public string Kdogumilce { get; set; }
        public string Kmahalle { get; set; }
        public string Kkoy { get; set; }
        public string Kcilt { get; set; }
        public string Kaile { get; set; }
        public string KSiraNo { get; set; }
        public string KVerilisYeri { get; set; }
        public string KKayitNo { get; set; }
    
        public virtual ICollection<Siniflar> Siniflars { get; set; }
    }
}
