//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwd
    {
        public string userid { get; set; }
        public string createpassword { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> yaş { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<int> yıl { get; set; }
        public string adres { get; set; }
        public string irtibatno { get; set; }
        public string şifre { get; set; }
        public string şifredoğrula { get; set; }
        public string comdepart { get; set; }
        public Nullable<int> gun { get; set; }
        public Nullable<int> ay { get; set; }
        public string confirmpassword { get; set; }
    }
}
