//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemirbasMekanlari
    {
        public int MekanId { get; set; }
        public int DemirbasId { get; set; }
        public string BulunduguYer { get; set; }
        public string Adet { get; set; }
        public string Sorumlusu { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
    
        public virtual Demirbaslar Demirbaslar { get; set; }
    }
}
