//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwd
    {
        public string userid { get; set; }
        public string createpassword { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public Nullable<int> year { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string comdepart { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> mount { get; set; }
        public string confirmpassword { get; set; }
    }
}
