//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public Siniflar()
        {
            this.Ogrencilers = new HashSet<Ogrenciler>();
            this.Yoklamas = new HashSet<Yoklama>();
        }
    
        public int sinifId { get; set; }
        public string sinifAdi { get; set; }
        public Nullable<int> sinifkapasite { get; set; }
        public Nullable<int> ögretmenId { get; set; }
    
        public virtual ICollection<Ogrenciler> Ogrencilers { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual ICollection<Yoklama> Yoklamas { get; set; }
    }
}
