//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersTablo
    {
        public int SINIFID { get; set; }
        public int CL0 { get; set; }
        public int CL1 { get; set; }
        public int CL2 { get; set; }
        public int CL3 { get; set; }
        public int CL4 { get; set; }
        public int CL5 { get; set; }
        public int CL6 { get; set; }
        public int CL7 { get; set; }
        public int CL8 { get; set; }
        public int CL9 { get; set; }
        public int CL10 { get; set; }
        public int CL11 { get; set; }
        public int CL12 { get; set; }
        public int CL13 { get; set; }
        public int CL14 { get; set; }
        public int CL15 { get; set; }
        public int CL16 { get; set; }
        public int CL17 { get; set; }
        public int CL18 { get; set; }
        public int CL19 { get; set; }
        public int CL20 { get; set; }
        public int CL21 { get; set; }
        public int CL22 { get; set; }
        public int CL23 { get; set; }
        public int CL24 { get; set; }
        public int CL25 { get; set; }
        public int CL26 { get; set; }
        public int CL27 { get; set; }
        public int CL28 { get; set; }
        public int CL29 { get; set; }
        public int CL30 { get; set; }
        public int CL31 { get; set; }
        public int CL32 { get; set; }
        public int CL33 { get; set; }
        public int CL34 { get; set; }
        public int CL35 { get; set; }
        public int CL36 { get; set; }
        public int CL37 { get; set; }
        public int CL38 { get; set; }
        public int CL39 { get; set; }
    
        public virtual DERSLER DERSLER { get; set; }
        public virtual DERSLER DERSLER1 { get; set; }
        public virtual DERSLER DERSLER2 { get; set; }
        public virtual DERSLER DERSLER3 { get; set; }
        public virtual DERSLER DERSLER4 { get; set; }
        public virtual DERSLER DERSLER5 { get; set; }
        public virtual DERSLER DERSLER6 { get; set; }
        public virtual DERSLER DERSLER7 { get; set; }
        public virtual DERSLER DERSLER8 { get; set; }
        public virtual DERSLER DERSLER9 { get; set; }
        public virtual DERSLER DERSLER10 { get; set; }
        public virtual DERSLER DERSLER11 { get; set; }
        public virtual DERSLER DERSLER12 { get; set; }
        public virtual DERSLER DERSLER13 { get; set; }
        public virtual DERSLER DERSLER14 { get; set; }
        public virtual DERSLER DERSLER15 { get; set; }
        public virtual DERSLER DERSLER16 { get; set; }
        public virtual DERSLER DERSLER17 { get; set; }
        public virtual DERSLER DERSLER18 { get; set; }
        public virtual DERSLER DERSLER19 { get; set; }
        public virtual DERSLER DERSLER20 { get; set; }
        public virtual DERSLER DERSLER21 { get; set; }
        public virtual DERSLER DERSLER22 { get; set; }
        public virtual DERSLER DERSLER23 { get; set; }
        public virtual DERSLER DERSLER24 { get; set; }
        public virtual DERSLER DERSLER25 { get; set; }
        public virtual DERSLER DERSLER26 { get; set; }
        public virtual DERSLER DERSLER27 { get; set; }
        public virtual DERSLER DERSLER28 { get; set; }
        public virtual DERSLER DERSLER29 { get; set; }
        public virtual DERSLER DERSLER30 { get; set; }
        public virtual DERSLER DERSLER31 { get; set; }
        public virtual DERSLER DERSLER32 { get; set; }
        public virtual DERSLER DERSLER33 { get; set; }
        public virtual DERSLER DERSLER34 { get; set; }
        public virtual DERSLER DERSLER35 { get; set; }
        public virtual DERSLER DERSLER36 { get; set; }
        public virtual DERSLER DERSLER37 { get; set; }
        public virtual DERSLER DERSLER38 { get; set; }
        public virtual DERSLER DERSLER39 { get; set; }
        public virtual Siniflar Siniflar { get; set; }
    }
}
