//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DERSLER
    {
        public DERSLER()
        {
            this.DersTablo = new HashSet<DersTablo>();
            this.DersTablo1 = new HashSet<DersTablo>();
            this.DersTablo2 = new HashSet<DersTablo>();
            this.DersTablo3 = new HashSet<DersTablo>();
            this.DersTablo4 = new HashSet<DersTablo>();
            this.DersTablo5 = new HashSet<DersTablo>();
            this.DersTablo6 = new HashSet<DersTablo>();
            this.DersTablo7 = new HashSet<DersTablo>();
            this.DersTablo8 = new HashSet<DersTablo>();
            this.DersTablo9 = new HashSet<DersTablo>();
            this.DersTablo10 = new HashSet<DersTablo>();
            this.DersTablo11 = new HashSet<DersTablo>();
            this.DersTablo12 = new HashSet<DersTablo>();
            this.DersTablo13 = new HashSet<DersTablo>();
            this.DersTablo14 = new HashSet<DersTablo>();
            this.DersTablo15 = new HashSet<DersTablo>();
            this.DersTablo16 = new HashSet<DersTablo>();
            this.DersTablo17 = new HashSet<DersTablo>();
            this.DersTablo18 = new HashSet<DersTablo>();
            this.DersTablo19 = new HashSet<DersTablo>();
            this.DersTablo20 = new HashSet<DersTablo>();
            this.DersTablo21 = new HashSet<DersTablo>();
            this.DersTablo22 = new HashSet<DersTablo>();
            this.DersTablo23 = new HashSet<DersTablo>();
            this.DersTablo24 = new HashSet<DersTablo>();
            this.DersTablo25 = new HashSet<DersTablo>();
            this.DersTablo26 = new HashSet<DersTablo>();
            this.DersTablo27 = new HashSet<DersTablo>();
            this.DersTablo28 = new HashSet<DersTablo>();
            this.DersTablo29 = new HashSet<DersTablo>();
            this.DersTablo30 = new HashSet<DersTablo>();
            this.DersTablo31 = new HashSet<DersTablo>();
            this.DersTablo32 = new HashSet<DersTablo>();
            this.DersTablo33 = new HashSet<DersTablo>();
            this.DersTablo34 = new HashSet<DersTablo>();
            this.DersTablo35 = new HashSet<DersTablo>();
            this.DersTablo36 = new HashSet<DersTablo>();
            this.DersTablo37 = new HashSet<DersTablo>();
            this.DersTablo38 = new HashSet<DersTablo>();
            this.DersTablo39 = new HashSet<DersTablo>();
        }
    
        public int DERSID { get; set; }
        public string DERSADI { get; set; }
        public int OGRETMENID { get; set; }
    
        public virtual ICollection<DersTablo> DersTablo { get; set; }
        public virtual ICollection<DersTablo> DersTablo1 { get; set; }
        public virtual ICollection<DersTablo> DersTablo2 { get; set; }
        public virtual ICollection<DersTablo> DersTablo3 { get; set; }
        public virtual ICollection<DersTablo> DersTablo4 { get; set; }
        public virtual ICollection<DersTablo> DersTablo5 { get; set; }
        public virtual ICollection<DersTablo> DersTablo6 { get; set; }
        public virtual ICollection<DersTablo> DersTablo7 { get; set; }
        public virtual ICollection<DersTablo> DersTablo8 { get; set; }
        public virtual ICollection<DersTablo> DersTablo9 { get; set; }
        public virtual ICollection<DersTablo> DersTablo10 { get; set; }
        public virtual ICollection<DersTablo> DersTablo11 { get; set; }
        public virtual ICollection<DersTablo> DersTablo12 { get; set; }
        public virtual ICollection<DersTablo> DersTablo13 { get; set; }
        public virtual ICollection<DersTablo> DersTablo14 { get; set; }
        public virtual ICollection<DersTablo> DersTablo15 { get; set; }
        public virtual ICollection<DersTablo> DersTablo16 { get; set; }
        public virtual ICollection<DersTablo> DersTablo17 { get; set; }
        public virtual ICollection<DersTablo> DersTablo18 { get; set; }
        public virtual ICollection<DersTablo> DersTablo19 { get; set; }
        public virtual ICollection<DersTablo> DersTablo20 { get; set; }
        public virtual ICollection<DersTablo> DersTablo21 { get; set; }
        public virtual ICollection<DersTablo> DersTablo22 { get; set; }
        public virtual ICollection<DersTablo> DersTablo23 { get; set; }
        public virtual ICollection<DersTablo> DersTablo24 { get; set; }
        public virtual ICollection<DersTablo> DersTablo25 { get; set; }
        public virtual ICollection<DersTablo> DersTablo26 { get; set; }
        public virtual ICollection<DersTablo> DersTablo27 { get; set; }
        public virtual ICollection<DersTablo> DersTablo28 { get; set; }
        public virtual ICollection<DersTablo> DersTablo29 { get; set; }
        public virtual ICollection<DersTablo> DersTablo30 { get; set; }
        public virtual ICollection<DersTablo> DersTablo31 { get; set; }
        public virtual ICollection<DersTablo> DersTablo32 { get; set; }
        public virtual ICollection<DersTablo> DersTablo33 { get; set; }
        public virtual ICollection<DersTablo> DersTablo34 { get; set; }
        public virtual ICollection<DersTablo> DersTablo35 { get; set; }
        public virtual ICollection<DersTablo> DersTablo36 { get; set; }
        public virtual ICollection<DersTablo> DersTablo37 { get; set; }
        public virtual ICollection<DersTablo> DersTablo38 { get; set; }
        public virtual ICollection<DersTablo> DersTablo39 { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
