//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaOkuluWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemekler
    {
        public int YemekId { get; set; }
        public string Corba { get; set; }
        public string AnaYemek { get; set; }
        public string Tatli { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
